config/routes.rb
Sitemarx::Application.routes.draw do
  resources :sitemarx_models
  
  

end

app/models/sitemarx_model.rb
class SitemarxModel < ActiveRecord::Base
	
	
	validates :name, presence: true, length: {minimum: 2, too_short: "must be atleast 2"}
	validates :url, presence: true
	
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sitemarx_models_controller.rb
class SitemarxModelsController < ApplicationController
  before_action :set_sitemarx_model, only: [:show, :edit, :update, :destroy]

  # GET /sitemarx_models
  # GET /sitemarx_models.json
  def index
    @sitemarx_models = SitemarxModel.all
  end

  # GET /sitemarx_models/1
  # GET /sitemarx_models/1.json
  def show
  end

  # GET /sitemarx_models/new
  def new
    @sitemarx_model = SitemarxModel.new
  end

  # GET /sitemarx_models/1/edit
  def edit
  end

  # POST /sitemarx_models
  # POST /sitemarx_models.json
  def create
    @sitemarx_model = SitemarxModel.new(sitemarx_model_params)

    respond_to do |format|
      if @sitemarx_model.save
        format.html { redirect_to @sitemarx_model, notice: 'Sitemarx model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sitemarx_model }
      else
        format.html { render action: 'new' }
        format.json { render json: @sitemarx_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sitemarx_models/1
  # PATCH/PUT /sitemarx_models/1.json
  def update
    respond_to do |format|
      if @sitemarx_model.update(sitemarx_model_params)
        format.html { redirect_to @sitemarx_model, notice: 'Sitemarx model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sitemarx_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sitemarx_models/1
  # DELETE /sitemarx_models/1.json
  def destroy
    @sitemarx_model.destroy
    respond_to do |format|
      format.html { redirect_to sitemarx_models_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sitemarx_model
      @sitemarx_model = SitemarxModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sitemarx_model_params
      params.require(:sitemarx_model).permit(:url, :name, :saved_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sitemarx_models_helper.rb
module SitemarxModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sitemarx</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sitemarx_models/_form.html.erb
<%= form_for(@sitemarx_model) do |f| %>
  <% if @sitemarx_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sitemarx_model.errors.count, "error") %> prohibited this sitemarx_model from being saved:</h2>

      <ul>
      <% @sitemarx_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :saved_at %><br>
    <%= f.datetime_select :saved_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sitemarx_models/edit.html.erb
<h1>Editing sitemarx_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @sitemarx_model %> |
<%= link_to 'Back', sitemarx_models_path %>

app/views/sitemarx_models/index.html.erb
<h1>Listing sitemarx_models</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Name</th>
      <th>Saved at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sitemarx_models.each do |sitemarx_model| %>
      <tr>
        <td><%= sitemarx_model.url %></td>
        <td><%= sitemarx_model.name %></td>
        <td><%= sitemarx_model.saved_at %></td>
        <td><%= link_to 'Show', sitemarx_model %></td>
        <td><%= link_to 'Edit', edit_sitemarx_model_path(sitemarx_model) %></td>
        <td><%= link_to 'Destroy', sitemarx_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sitemarx model', new_sitemarx_model_path %>

app/views/sitemarx_models/new.html.erb
<h1>New sitemarx_model</h1>

<%= render 'form' %>

<%= link_to 'Back', sitemarx_models_path %>

app/views/sitemarx_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @sitemarx_model.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sitemarx_model.name %>
</p>

<p>
  <strong>Saved at:</strong>
  <%= @sitemarx_model.saved_at %>
</p>

<%= link_to 'Edit', edit_sitemarx_model_path(@sitemarx_model) %> |
<%= link_to 'Back', sitemarx_models_path %>